spring.application.name=My-Pet
# Cambiar el puerto para que no choque con otros proyectos
server.port=8082

# Configuración de la Base de Datos MySQL (Apunta a tu base de datos "mypet")
spring.datasource.url=jdbc:mysql://localhost:3306/mypet?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# Propiedades de Hibernate para que Spring cree las tablas solo
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.web=DEBUG